### ISSUE TITLE
Can we convert docker-compose.yaml to dart?

### ISSUE THREAD

**Issue by yahu1031** [noojee/docker2#2]
I have a docker-compose.yaml file as follows
```yaml
version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: testing
      POSTGRES_PASSWORD: Q86eglMdu40dYvwuFjuNJp8Y4lWAzhjw
    volumes:
      - testing_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass hQGpD4d5nP5vTbNXnKhnd1pF0Y4y8ltf
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  testing_data:

```
Would like to use docker2 package and how could I do it?

**Comment by bsutton** [comment]
yahu,
so I'm going to give you the benefit of the doubt and assume that you are new to open source and explain how this process works.

Open source developers are not here to do your work for you. Happy to help and point you in the right direction but you first need to demonstrate that you have put some effort into working it out for yourself.

The contents of your issue suggest that you have made zero effort to investigate how the work might be done.

So come back after you have tried a few things, ask some specific questions and I will only be too willing to help.

But I'm not here to do your homework.

**Comment by yahu1031** [comment]
Haha, thanks for the reply mate @bsutton, Actually I have tried running `dockerRun()`, But doesn't work out. So just making sure if there is any resource that could handle the docker without `docker-compose.yaml`. Using this part is the problem. 

```yaml
environment:
  POSTGRES_USER: postgres
  POSTGRES_DB: testing
  POSTGRES_PASSWORD: Q86eglMdu40dYvwuFjuNJp8Y4lWAzhjw
volumes:
  - testing_data:/var/lib/postgresql/data
```

If there is a way, just ping me up the docs, please. I will read and learn myself.
